import type { Metadata } from 'next';
import './globals.css';
import { DM_Sans, MuseoModerno } from 'next/font/google';
import NavBar from '@/components/navbar/nav-bar';
import { Toaster } from '@/components/ui/sonner';

const dm_sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm_sans',
});
const museoModerno = MuseoModerno({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-museoModerno',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body
        className={'h-full bg-white' + museoModerno.variable + dm_sans.variable}
      >
        <NavBar />
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
