import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navbar/nav-bar";
import { DM_Sans } from "next/font/google";
import { MuseoModerno } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm_sans",
});
const museoModerno = MuseoModerno({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-museoModerno",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={"h-full bg-white" + museoModerno.variable + dm_sans.variable}
      >
        <NavBar />
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
